version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true" ## permite o fast refresh no browser
    command: yarn start ## comando a executar
    ports:
      - "3000:3000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    stdin_open: true ## roda shell em modo interativo
    volumes:
      - .:/usr/app_react ## monitora a pasta atual . e envia as alterações para /usr/app_react